In [4]:
import numpy as np
a=np.array([20,30,40])
b=np.array([40,50,60])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[20 30 40]
[40 50 60]
[ 60  80 100]
[-20 -20 -20]
[ 800 1500 2400]


In [20]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0:2,0:2])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))

[[1 2]
 [4 5]]
(2, 3)
6
2


In [32]:
a=[1,2,3,4,5,6]
arr=np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(arr.astype(float))
print(arr)

[1 2 3 4 5 6]
(6,)
6
1
int64
6
[1. 2. 3. 4. 5. 6.]
[1 2 3 4 5 6]


In [46]:
# Functions in Numpy for Addition,Subtract,Multiply,Square,exp,Divide
a=[111,1111,11111]
b=[1111,11111,11111]
arr1=np.array([a,b])
arr2=np.array([b,a])
print(np.add(arr1,arr2))# print(arr1+arr2)

print(np.subtract(arr1,arr2))  #print(arr1-arr2)
print(np.square(arr1))
print(np.power(arr1,3))
# print(arr2)

[[ 1222 12222 22222]
 [ 1222 12222 22222]]
[[ -1000 -10000      0]
 [  1000  10000      0]]
[[    12321   1234321 123454321]
 [  1234321 123454321 123454321]]
[[      1367631    1371330631 1371700960631]
 [   1371330631 1371700960631 1371700960631]]


In [55]:
# Combining and Splitting The Array --> Concatenate Fun to combine
print(np.concatenate([arr1,arr2],axis=1))
print(np.hstack([arr1,arr2]))
print(np.vstack([arr1,arr2]))
arrr=[1,2,3,4,5,6]
aa=np.array(arrr)
print(aa)
b=np.array_split(aa,2)
print(b[0])

[[  111  1111 11111  1111 11111 11111]
 [ 1111 11111 11111   111  1111 11111]]
[[  111  1111 11111  1111 11111 11111]
 [ 1111 11111 11111   111  1111 11111]]
[[  111  1111 11111]
 [ 1111 11111 11111]
 [ 1111 11111 11111]
 [  111  1111 11111]]
[1 2 3 4 5 6]
[1 2 3]


In [60]:
#Adding and removing elements in the Array
a=np.array([20,40,60,80])
print(a)
a=np.append(a,[90,100])
print(a)
a=np.insert(a,[0,2],55) # We can add val at multiple locations
print(a)

[20 40 60 80]
[ 20  40  60  80  90 100]
[ 55  20  40  55  60  80  90 100]


In [75]:
# SORT,FILTER and Search
w=np.array([3,4,5,2,1,7,6,54])
print(w)
ww=np.sort(w)
print(np.where(w%3==0))
print(np.searchsorted(ww,4))
fa=[True,False,True,True,True,True,True,True] # Filtering
fb=w>3
fc=w%2==0
print(w[fb])
print(w[fa])
print(w[fc])


[ 3  4  5  2  1  7  6 54]
(array([0, 6, 7]),)
3
[ 4  5  7  6 54]
[ 3  5  2  1  7  6 54]
[ 4  2  6 54]


In [90]:
# Aggregating Functions in NumPy
# x=np.array([2,3,4,5])
# print(np.sum(x))
# print(np.prod(x))
# print(np.max(x))
# print(np.min(x))
# print(np.size(x))
# print(np.mean(x))
# print(np.median(x))
# print(np.cumsum(x))
# print(np.cumprod(x))

a=[100,250,200,199,20]
b=[5,10,15,40,6]
prices=np.array(a)
quantity=np.array(b)
print(prices)
print(quantity)
total=np.cumprod([prices,quantity],axis=0)
print()
print(total[1])
print("Total=",total[1].sum())
# print(np.cumprod([prices,quantity],axis=1))



[100 250 200 199  20]
[ 5 10 15 40  6]

[ 500 2500 3000 7960  120]
Total= 14080


In [97]:
carbs=[120,150,90,60,130,80,90]
weight=[70,70,80,90,50,80,65]
w=np.array(carbs)
ww=np.array(weight)
print(np.corrcoef(w,ww))  # correlation if -ve (inversly propotional),+ve ( directly),0(No Comparison)
# print(np.mean(w))
# print(np.median(w))
# print(np.std(w))
# import statistics as st  # NumPy dont have fun of Mode so we included this Lib.
# print(st.mode(w))

[[ 1.         -0.69691415]
 [-0.69691415  1.        ]]
